language: python
python:
  - 2.7
  - 3.4

before_install:
- pip install git+git://github.com/AlienVault-Labs/OTX-Python-SDK.git

before_script:
 - chmod +x ./otx-suricata/test_rules.py

# command to run tests
script: python ./otx-suricata/test_rules.py